#!/bin/bash
set -e

NOTIFY_TOPIC=$1
NOTIFY_PROTOCOL=$2
NOTIFY_HOST=$3
NOTIFY_PORT=$4
HOSTNAME=$(hostname)

if [ "$#" -ne 4 ]; then
  printf "Usage:\n"
  printf "  naivepatch <topic> <protocol> <host> <port>\n"
  exit 1
fi

# Supporting functions
notify() {
  echo -n "pub #$NOTIFY_TOPIC $1" > /dev/$NOTIFY_PROTOCOL/$NOTIFY_HOST/$NOTIFY_PORT
}

apt() {
  printf "NAIVEPATCH apt-get $1 ...\n"
  sudo apt-get -y $1
}

# Main
printf "\n---------------------------------------------------\n"
printf "NAIVEPATCH "

DATETIME=$(date "+%Y-%m-%d %H:%M:%S %Z")
printf $DATETIME
notify "$DATETIME $HOSTNAME start"

TMP_SHA_SUM=$(shasum /usr/local/bin/naivepatch)
PATCH=${TMP_SHA_SUM:0:12}
printf " v.$PATCH\n"

apt autoclean
apt autoremove
apt update
apt dist-upgrade

printf "\nNAIVEPATCH rebooting ...\n"
notify "$DATETIME $HOSTNAME reboot"
sudo reboot
